apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: grafana
      version: 10.5.15
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
  values:
    persistence:
      enabled: true
      size: 5Gi
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Loki
            type: loki
            access: proxy
            url: http://loki.monitoring.svc.cluster.local:3100
            isDefault: true
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"
        folderAnnotation: grafana_folder
        searchNamespace: monitoring
        provider:
          allowUiUpdates: true
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - grafana.christou.cloud
      tls:
        - hosts:
            - grafana.christou.cloud
