apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    service:
      type: LoadBalancer
    ports:
      imaps:
        port: 993
        expose:
          default: true
        exposedPort: 993
        protocol: TCP
